<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "emailPhoneSync": {
                    "component": "MagoArab_WithoutEmail/js/email-phone-sync"
                }
            }
        }
    }
}
</script>

<style>
#customer-email-fieldset {
    position: absolute !important;
    left: -9999px !important;
    top: -9999px !important;
    opacity: 0 !important;
}
</style>